### ISSUE TITLE
Example: Build the test archive (.war) during test

### ISSUE THREAD

**Issue by rmpestano** [primefaces-extensions/primefaces-arquillian#1]
Currently this project relies on an already builded war file on target folder ([see here](https://github.com/primefaces-extensions/primefaces-arquillian/blob/8312cf71ae6c5f22c03d17e407e930d9c5c7a044/primefaces-arquillian-example/src/test/java/org/primefaces/extensions/arquillian/example/IndexPageTest.java#L34)). This may cause issues specially when you run the test from the IDE, e.g you updated the project and forget to build it then your tests will run on top of old code.

A more automatic approach is to build the binary on the deployment method, see an [example here](https://github.com/rmpestano/cdi-crud/blob/master/src/test/java/com/cdi/crud/test/infra/CdiCrudAutomaticDeployment.java#L36), also a blog post about it [here.](https://rpestano.wordpress.com/2015/11/12/the-simplest-micro-deployment-arqtip-2/)

I can contribute if you agree.

**Comment by tandraschko** [comment]
Yep thats true but its a Bit easier this way. Not sure whats better, maybe we should just describe both ways

**Comment by tandraschko** [comment]
But maybe it makes sense to change if you have problems. So +1

**Comment by tandraschko** [comment]
(PR welcome @rmpestano :D)

**Comment by rmpestano** [comment]
This one is not so easy as I thought because I need to figure out how to build (install) PrimeFacesArquillian lib and then create the example project war, all using EmbbededMaven.

**Comment by tandraschko** [comment]
fixed

**Comment by rmpestano** [comment]
The shrinkwrap bom should be on `<dependencyManagement` section, no? https://github.com/primefaces-extensions/primefaces-arquillian/commit/079a0ec379fd811ba52e8a1f911954b1e7797ffa#diff-9b5c904ea89caf326f6c49605f8bec44R103

then you don't need to reference the version in the [depchain here](https://github.com/primefaces-extensions/primefaces-arquillian/blob/adc2f6186a6a3eb795ad463db25cb1f66949abe0/primefaces-arquillian/pom.xml#L110).

PS: it would be nice to reference the issue on the commit, it makes easier to track changes.
