### ISSUE TITLE
Activate Travis CI for the project

### ISSUE THREAD

**Issue by krichter722** [primefaces-extensions/primefaces-arquillian#11]
The `.travis.yml` has been merged, however it has no effect because commits and PRs are not checked as long as the project isn't activated. You can do that on https://www.travis-ci.org/primefaces-extensions/primefaces-arquillian.

dependent: #6

**Comment by tandraschko** [comment]
refactored the whole structure
we need a better travis xml now

**Comment by krichter722** [comment]
@tandraschko I'm always a fan of keeping the CI script very close to the build instructions (ideally only run commands which make up the build instructions), although I see the advantage of parallelization. And there's the need to prepare CD artifacts. Do you have something else in mind? How is CD handled in PrimeFaces extensions?

**Comment by tandraschko** [comment]
no idea :D @melloware do we have CD for PFE?

**Comment by melloware** [comment]
the only thing we have is a travis CI project to build upon check in but its not releasing the artifacts anywhere public.

https://github.com/primefaces-extensions/core/blob/master/.travis.yml

**Comment by krichter722** [comment]
Adjustment to new directory structure is handled in #11. Afaik the Travis project can be activated after #11 has been merged.

**Comment by krichter722** [comment]
@tandraschko I mean #15, sorry. Travis can be activated, now.

**Comment by tandraschko** [comment]
how can i do that? do i need a account there?

**Comment by krichter722** [comment]
No, it's accessible through OAuth based on your GitHub account. It'll recognize you as owner and opening https://travis-ci.org/primefaces-extensions/primefaces-arquillian should allow you to activate the project.

**Comment by tandraschko** [comment]
done! :D
would you like to add the travis icon like in PrimeFaces to this project?

**Comment by krichter722** [comment]
Thanks for the quick maintenance session :). Sure! #18
