### ISSUE TITLE
Dicuss versioning

### ISSUE THREAD

**Issue by tandraschko** [primefaces-extensions/primefaces-arquillian#13]
@rmpestano @krichter722 @melloware 
Which version number pattern should we use?

I thought about reusing the primefaces version + append our release version.

So the first release, based on 6.2 would be: 6.2.1
The second release for 6.2 would be: 6.2.2

The first release based on 6.3 would be: 6.3.1

Current master would be 6.2.1-SNAPSHOT then

**Comment by krichter722** [comment]
Imo that only makes sense if the coupling is very strong, i.e. if a lot of changes in Primefaces require changes in primefaces-arquillian. A double version can be used to express an association with a Primefaces version, e.g. `1.1.2-6.3`, but I'm not sure if Maven and all used plugins using the version accept this. A custom version is always less troublesome and it shouldn't be too difficult to figure out which min. version is necessary to be able to test with a certain Primefaces version.

**Comment by rmpestano** [comment]
I think proposed pattern by Thomas is ok the only drawback to me is that it doesn't follow https://semver.org/ and may confuse users. On the other hand I've used [arquillian-universe](https://search.maven.org/search?q=arquillian%20universe)  and they prefix arquillian-core version the same way Thomas proposed and it just works.

Another option would be having primefaces-arquillian 1.0 targeting PF 6.2, primefaces-arquillian 2.0 with PF 6.3 and so on. The drawback of this option is that users must read the docs to know which PrimeFaces version the PrimeArquillian is targeting.

**Comment by tandraschko** [comment]
OK, then lets to do it like i menteioned.
PF Extensions itself uses the same pattern.
