### ISSUE TITLE
Provide Maven Javadoc and source artifacts

### ISSUE THREAD

**Issue by krichter722** [primefaces-extensions/primefaces-arquillian#4]
Maven Javadoc and source artifacts allow it to gain quick and uncomplicated access to the documentation in almost all modern IDE and to take a look at an implementation detail in case suspicion about correct implementation arises.

The deployment of the Javadoc and sources artifact should be included in the CI/CD processes. I don't know how they work in PrimeFaces or PrimeFaces extensions. I could suggest a PR, but it'd only be the addition of the `maven-javadoc-plugin` and `maven-sources-plugin` without me knowing whether that does the trick.

**Comment by tandraschko** [comment]
please provide a PR

**Comment by tandraschko** [comment]
i mean for the javadoc and sources generation

not sure, do we have a configured travis for PFE @melloware?

This project also misses a lot of configureation like release plugin and else.
Do you have time to configure it melloware?
Did you ever thought about removing the annoying master-pom?
MasterPOMs actually always starting smart and small but check ours.. we have dependencies for gson etc. there, which are completely uninteressted for this project here.
I would like to see this project working without the master-pom stuff.

**Comment by krichter722** [comment]
It seems like no snapshots of the project are available, so I'll postpone until the CD is configured.

**Comment by tandraschko** [comment]
added the plugins
