### ISSUE TITLE
Example: Download webdriver automactly

### ISSUE THREAD

**Issue by rmpestano** [primefaces-extensions/primefaces-arquillian#7]
Currently the project uses fixed path for chrome driver binary: 
```
ERROR] myFirstTest(org.primefaces.extensions.arquillian.example.IndexPageTest)  Time elapsed: 0.049 s  <<< ERROR!
java.lang.IllegalArgumentException: The file D:/chromedriver.exe does not exist
```

The binary can be downloaded by drone, [see docs here](http://arquillian.org/arquillian-extension-drone/#_automatic_download).

**Comment by tandraschko** [comment]
can this be automated somehow? Or do you think we should put the driver in the example src?

**Comment by rmpestano** [comment]
Yes, by just removing the property `chromeDriverPath` in arquillian.xml, here's what I have here:

```
 <extension qualifier="webdriver">
        <property name="browser">chrome</property>
        <property name="chromeDriverVersion">2.40</property> <!-- if not set drone will download latest version -->
    </extension>
```

**Comment by tandraschko** [comment]
Ok, a PR would be great!
